# Generated by Django 4.2.6 on 2023-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="size_new",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
