# Generated by Django 4.2.6 on 2023-11-12 17:36

# Generated by Django 4.2.6 on 2023-11-12 17:26

from django.db import migrations


def transfer_data(apps, schema):
    Application = apps.get_model("applications", "Application")
    applications = Application.objects.all()
    for application in applications:
        application.size_new = application.size
        application.save(update_fields=["size_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_application_size_new"),
    ]

    operations = [
        migrations.RunPython(code=transfer_data),
    ]
