# Generated by Django 4.0 on 2022-10-20 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("vps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vps",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
