# Generated by Django 4.2.6 on 2023-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vps", "0004_vps_deployed_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vps",
            name="cpu",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vps",
            name="hdd",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vps",
            name="ram",
            field=models.PositiveIntegerField(),
        ),
    ]
